### PR TITLE
Fix confirmation prompt on windows

### LINKED ISSUE #439: Action confirmation prompt doesn't work on windows
When running the command:
```sh
vegawallet delete --wallet WALLET
```

the user is asked to confirm his request. On windows, the confirmation message fails to be recognized.

This is probably because windows is adding a `\r` in the response that is not stripped before comparaison.

### PR DESCRIPTION
**Pull request by ValentinTrinque**
Close #439

### CODE REVIEW

**Comment by ValentinTrinque** [comment]
@VegaJakeg as  a windows user can you verify this behavior and the fix ? Thanks.

**Review by pscott31 — APPROVED** [review]

File: cmd/flags/force.go [hunk 1]
```diff
@@ -19,7 +19,7 @@ func DoYouConfirm() (bool, error) {
 	}
 	fmt.Println() //nolint:forbidigo
 
-	answer = strings.ToLower(strings.Trim(answer, " \n\t"))
+	answer = strings.ToLower(strings.Trim(answer, " \r\n\t"))
```
Comment (pscott31) [inline cmd/flags/force.go:22]: Does this cause any bother on linux/macos? I wonder if there's go constant that evaluates to the RightThing(tm) for the platform

Comment (pscott31) [reply cmd/flags/force.go:22]: Actually ignore me, I see that's a set of characters to trim not something you're adding :)

**Review by jgsbennett — APPROVED** [review]
